Name:           ros-indigo-convenience-ros-functions
Version:        1.0.0
Release:        0%{?dist}
Summary:        ROS convenience_ros_functions package

Group:          Development/Libraries
License:        GPLv3
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-actionlib
Requires:       ros-indigo-baselib-binding
Requires:       ros-indigo-convenience-math-functions
Requires:       ros-indigo-eigen-conversions
Requires:       ros-indigo-geometry-msgs
Requires:       ros-indigo-rosbag
Requires:       ros-indigo-roscpp
Requires:       ros-indigo-sensor-msgs
Requires:       ros-indigo-tf
Requires:       ros-indigo-trajectory-msgs
BuildRequires:  ros-indigo-actionlib
BuildRequires:  ros-indigo-baselib-binding
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-convenience-math-functions
BuildRequires:  ros-indigo-eigen-conversions
BuildRequires:  ros-indigo-geometry-msgs
BuildRequires:  ros-indigo-rosbag
BuildRequires:  ros-indigo-roscpp
BuildRequires:  ros-indigo-sensor-msgs
BuildRequires:  ros-indigo-tf
BuildRequires:  ros-indigo-trajectory-msgs

%description
Provides a variety of convenience functions for certain ROS messages

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Thu Jun 09 2016 Jennifer Buehler <jennifer.e.buehler@gmail.com> - 1.0.0-0
- Autogenerated by Bloom

* Fri Jun 03 2016 Jennifer Buehler <jennifer.e.buehler@gmail.com> - 0.0.4-0
- Autogenerated by Bloom

* Wed Jun 01 2016 Jennifer Buehler <jennifer.e.buehler@gmail.com> - 0.0.3-1
- Autogenerated by Bloom

* Wed Jun 01 2016 Jennifer Buehler <jennifer.e.buehler@gmail.com> - 0.0.3-0
- Autogenerated by Bloom

* Wed Jun 01 2016 Jennifer Buehler <jennifer.e.buehler@gmail.com> - 0.0.2-1
- Autogenerated by Bloom

* Tue May 31 2016 Jennifer Buehler <jennifer.e.buehler@gmail.com> - 0.0.2-0
- Autogenerated by Bloom

* Mon May 30 2016 Jennifer Buehler <jennifer.e.buehler@gmail.com> - 0.0.1-0
- Autogenerated by Bloom

